### ISSUE TITLE
Is possible to use a 3D LiDAR in a RRBaseRobot to detect the movable parts of the robot itself?

### ISSUE THREAD

**Issue by dbarrita** [rapyuta-robotics/RapyutaSimulationPlugins#203]
Hi, I'm using the plugin to create a few RRBaseRobot and I have put 3D LiDARS on them. The LiDAR works properly the problem if that doesn't detect the elements of the RRBaseRobot itself (car with black wheels in the image). If I want to use LiDAR for detects the position of a movable part of my robot

![RRBaseRobot_3DLiDAR_issue](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/90312492/a24d9036-fa55-492d-b56d-b70e725e10d1)

How can I put the LiDAR as part of the RRBaseRobot and detect the robot parts? I need to create another RRBaseRobot that only have the LiDAR and attach it to my robot?

Thanks for your time and for develop this plugin.

**Comment by yuokamoto** [comment]
I merged one PR. Could you try again?
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/pull/196

it maybe just visualize lidar point always top

**Comment by dbarrita** [comment]
Thanks for the quick response, I have made the following steps:

- Make a pull of the devel branch
- Run the .../GenerateProjectFiles.sh file
- Run $ make (_my_package_name_)Editor

After that the problem persists the sensor detects other RRBaseRobot elements but not the meshes that belongs to the same RRBaseRobot. I check it on RViz and the pointcloud published is the same that it's seen in Unreal

**Comment by yuokamoto** [comment]
I created PR. Please check
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/pull/210

**Comment by dbarrita** [comment]
I have tested with LiDAR 3D and 2D and the problem persists. I have tried changing the new variable "_Ignore Self_" in the editor to false but the result is the same as when it's true.

![Lidar2D_ignore_self](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/90312492/2b874a45-7f80-43fa-b3cd-eafdf0ac61d7)
I have added a little shape to the turtlebot example to test the changes.

**Comment by yuokamoto** [comment]
hmm, this is test result for me. 

https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/16463135/d524402e-5c1e-4f05-b150-f634da2f94e8

**Comment by dbarrita** [comment]
Thanks! It works with the 2D LiDAR but I'm trying with the 3D and it doesn't work. Maybe I'm doing something wrong.



https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/90312492/ad1d0263-bd75-45f0-b392-e671ec4b3e61

**Comment by dbarrita** [comment]
I have been trying the LiDAR 3D but I can't make it work. With the 2D the behavior is the expected, with the "Ignore Self" parameter I can select the detection of the robot or not. But with the 3D doesn't work. I'm using the actual devel branch, because I have seen that the #210 is merged.

**Comment by yuokamoto** [comment]
Thanks for reporting. Let me check later.

**Comment by yuokamoto** [comment]
Found bug and created PR
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/pull/214

**Comment by dbarrita** [comment]
Solved! Now it's working properly. Thank you for your time.
![Captura desde 2023-10-09 14-27-44](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/assets/90312492/bec0e2e8-3fcd-4e16-987f-d6044cd37552)
